[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
capmon_staking = "FSenbAEVTgTdfM2723xkk8A2Y5oD8wtmB2EhiWXzpqSg"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
